apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hr-system-cert
  namespace: hr-system
spec:
  secretName: hr-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 'hr.example.com'
  dnsNames:
    - 'hr.example.com'